name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - "environment.yml"      

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          shm-size: 2g
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/natcap-invest-docker:latest